version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${NEXT_PUBLIC_PAYPAL_CLIENT_ID}
    ports:
      - "3000:3000"
    image: webapp
    environment:
      - DATABASE_URL="file:./db.sqlite"
        NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        NEXTAUTH_URL="http://localhost:3000"
        AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
        AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
