version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PAYPAL_CLIENT_ID: "AUGJzcaSSyEX2SjL_IG1eObYJm-uJ9FhOt-Gz5xBBKXp-YS-23crCsikUm2GFF8_vsxmqqk0MKcHXdb1"
    working_dir: /app
    ports:
      - "3000:3000"
    image: webapp
    environment:
      - DATABASE_URL="file:./db.sqlite"
        NEXTAUTH_SECRET="nextauth"
        NEXTAUTH_URL="http://localhost:3000"
        AUTH0_ISSUER_BASE_URL="https://dev-7a34ynmtyvgjvx5t.us.auth0.com"
        AUTH0_CLIENT_ID="jen1uwsV61ohdl3TNNlKwUcnxDxLswYV"
        AUTH0_CLIENT_SECRET="RQSl7D7X0QoQHIKJsbPRb2xDAi5GlUdBPOSYbRmEKsHtA423IDyZchMkMJbmgsUB"
